# Generated by Django 4.2.21 on 2025-10-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom'), ('admin', 'Admin')], db_index=True, default='monthly', max_length=20),
        ),
    ]
