# Generated by Django 4.2.21 on 2025-10-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
