# Generated by Django 4.2.21 on 2025-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(db_index=True, default='easypay', max_length=20),
        ),
    ]
