# Generated by Django 4.2.21 on 2025-07-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_last_grade_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Kashmir', 'Azad Kashmir'), ('Khyber-Pakhtunkhwa', 'Khyber-Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Federal Territory', 'Federal Territory')], max_length=50, null=True),
        ),
    ]
