# Generated by Django 4.2.21 on 2025-11-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_grade_alter_user_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fee_receipt',
        ),
    ]
