# Generated by Django 4.2.21 on 2026-03-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_topic_week_and_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('grade', 'order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='topicquiz',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('grade', 'order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='weekquiz',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topicquiz',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='week',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weekquiz',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
