# Generated by Django 5.2.4 on 2026-03-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_weekprogress_topicprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.subject'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('grade', 'subject', 'order'), name='uniq_week_grade_subject_order'),
        ),
    ]
