# Generated by Django 4.2.21 on 2026-06-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_week_subject_and_unique_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Kashmir', 'Azad Kashmir'), ('Khyber-Pakhtunkhwa', 'Khyber-Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Federal Territory', 'Federal Territory')], max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('plan_tier', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('enterprise', 'Enterprise')], default='small', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending_payment', max_length=20)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('onboarding_status', models.CharField(choices=[('registered', 'Registered'), ('paid', 'Paid'), ('roster_uploaded', 'Roster Uploaded'), ('active', 'Active')], default='registered', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'city'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.school'),
        ),
    ]
