# Generated by Django 4.2.21 on 2026-06-12 07:00

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_school_foundation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('city'), name='uniq_school_name_city_ci'),
        ),
    ]
