# Generated by Django 4.2.21 on 2026-06-12 13:04

from django.db import migrations, models
import django.db.models.deletion


def backfill_teachertask_school(apps, schema_editor):
    TeacherTask = apps.get_model("core", "TeacherTask")
    User = apps.get_model("core", "User")
    for task in TeacherTask.objects.filter(school__isnull=True).iterator():
        try:
            teacher = User.objects.get(pk=task.teacher_id)
        except User.DoesNotExist:
            continue
        if teacher.school_id:
            task.school_id = teacher.school_id
            task.save(update_fields=["school_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_school_name_city_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertask',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_tasks', to='core.school'),
        ),
        migrations.RunPython(backfill_teachertask_school, migrations.RunPython.noop),
    ]
